name: Security Scan

name: DevSecOps Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security-scan:
    runs-on: ubuntu-latest
    env:
      TIMESTAMP: ${{ github.run_id }}-${{ github.run_number }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up scan folder
        run: mkdir -p scans

      - name: Run Trivy filesystem scan
        run: trivy fs . > scans/trivy-${{ env.TIMESTAMP }}.txt

      - name: Run Semgrep scan
        run: semgrep scan --config auto > scans/semgrep-${{ env.TIMESTAMP }}.txt

      - name: Run GitLeaks scan
        run: gitleaks detect --source . --no-banner > scans/gitleaks-${{ env.TIMESTAMP }}.txt

      - name: Upload Scan Reports
        uses: actions/upload-artifact@v4
        with:
          name: security-reports-${{ env.TIMESTAMP }}
          path: scans/
