name: Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security-scan:
    runs-on: ubuntu-latest
    env:
      TIMESTAMP: ${{ github.run_id }}-${{ github.run_number }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create scans folder
        run: mkdir -p scans

      # -------------------------------
      #    Install Trivy
      # -------------------------------
      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install wget apt-transport-https gnupg lsb-release -y
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo "deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install trivy -y

      - name: Run Trivy filesystem scan
        run: trivy fs . > scans/trivy-${{ env.TIMESTAMP }}.txt

      # -------------------------------
      #    Install Semgrep
      # -------------------------------
      - name: Install Semgrep
        run: |
          pip install semgrep

      - name: Run Semgrep scan
        run: semgrep scan --config auto > scans/semgrep-${{ env.TIMESTAMP }}.txt

      # -------------------------------
      #    Install GitLeaks
      # -------------------------------
      - name: Install GitLeaks
        run: |
          curl -sSL https://github.com/gitleaks/gitleaks/releases/download/v8.18.2/gitleaks_8.18.2_linux_x64.tar.gz -o gitleaks.tar.gz
          tar -xzf gitleaks.tar.gz
          chmod +x gitleaks
          sudo mv gitleaks /usr/local/bin/gitleaks

      - name: Run GitLeaks scan
        run: gitleaks detect --source . --no-banner > scans/gitleaks-${{ env.TIMESTAMP }}.txt

      # -------------------------------
      #    Upload scan reports
      # -------------------------------
      - name: Upload Scan Reports
        uses: actions/upload-artifact@v4
        with:
          name: security-reports-${{ env.TIMESTAMP }}
          path: scans/
